# Generated by Django 3.0.7 on 2020-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('hit', models.IntegerField(default='0')),
            ],
        ),
    ]
